export const LOADING_FORM = 'LOADING_FORM';
export const CLEAR_LOADING_FORM = 'CLEAR_LOADING_FORM';
export const CLASSIFY_ADD_CLASS = 'CLASSIFY_ADD_CLASS';
export const CLASSIFY_DELETE_CLASS = 'CLASSIFY_DELETE_CLASS';
export const CLASSIFY_CURRENT_CLASS = 'CLASSIFY_CURRENT_CLASS';
