export const LOADING_FORM = 'LOADING_FORM';
export const CLEAR_LOADING_FORM = 'CLEAR_LOADING_FORM';
export const IMAGE_ADD_CLASS = 'IMAGE_ADD_CLASS';
export const IMAGE_DELETE_CLASS = 'IMAGE_DELETE_CLASS';
